import { BookOpen, Braces, Database, GitBranch } from 'lucide-react'

export default function About() {
  return <div className="page-stack"><section className="page-intro"><span className="kicker">About the work</span><h1>A reproducible case study, built for scrutiny.</h1><p>CreditWise turns exploratory notebooks into a focused analysis product with a versioned training pipeline, a held-out evaluation, and an interface that exposes what the data and model can actually support.</p></section>
    <section className="about-principles">{[[Database, 'Evidence first', 'Every chart comes from the bundled dataset through documented API aggregates.'], [GitBranch, 'One evaluation protocol', 'A stratified train, validation, and test split keeps threshold choice away from the test set.'], [Braces, 'Production-shaped', 'Typed requests, saved artifacts, tests, and deployable frontend and API demonstrate the full workflow.'], [BookOpen, 'Honest scope', 'The output models historical labels. It is not a credit policy or a repayment estimate.']].map(([Icon, title, text]) => <article key={String(title)}><Icon /><h2>{String(title)}</h2><p>{String(text)}</p></article>)}</section>
    <section className="case-study"><div><span className="kicker">Project architecture</span><h2>Notebook findings became testable software.</h2></div><ol><li><strong>Audit the source</strong><span>Normalize types, preserve missing targets, fingerprint the dataset.</span></li><li><strong>Run controlled experiments</strong><span>Compare candidates with identical folds and choose a threshold on validation data.</span></li><li><strong>Freeze evidence</strong><span>Save the pipeline, feature order, metrics, dataset hash, and runtime versions together.</span></li><li><strong>Serve the result</strong><span>Expose aggregated exploration and inference behind a typed API and accessible UI.</span></li></ol></section>
    <section className="scope-note"><h2>Responsible use</h2><p>This portfolio project is for analysis and demonstration. Dataset provenance, currency, income period, and licensing still require confirmation before any real-world reuse. Protected attributes are excluded from the public model, though their presence in the source can still be inspected for data auditing.</p></section>
  </div>
}
