import { AlertTriangle, CheckCircle2, Layers3, Target } from 'lucide-react'
import { number, pct, pretty } from '../data'
import type { ModelMetadata } from '../types'

const publicFeatures = ['Applicant_Income', 'Coapplicant_Income', 'Dependents', 'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings', 'Collateral_Value', 'Loan_Amount', 'Loan_Term', 'Employment_Status', 'Loan_Purpose', 'Property_Area', 'Education_Level', 'Employer_Category']

export default function Model({ metadata }: { metadata?: ModelMetadata }) {
  if (!metadata) return <div className="page-stack"><section className="page-intro"><span className="kicker">Current model</span><h1>Evaluation evidence is unavailable.</h1><p>Connect the API and train the documented artifact to load metrics. No older notebook score is substituted.</p></section><div className="offline-panel"><AlertTriangle /><h2>Current artifact required</h2><p>The model page deliberately avoids cached or historical metrics when the active artifact cannot be verified.</p></div></div>
  const matrix = metadata.test.confusion
  const candidates = metadata.candidate_ranking.slice(0, 6)
  return <div className="page-stack"><section className="page-intro model-intro"><div><span className="kicker">Current model · artifact {metadata.model_version}</span><h1>Model evaluation</h1><p>The decision threshold was selected on validation data. The test set was evaluated once at that frozen threshold.</p></div><div className="artifact-stamp"><CheckCircle2 /><span>Results generated<strong>{new Date(metadata.created_at).toLocaleDateString()}</strong></span></div></section>
    <section className="metric-strip" aria-label="Held-out test metrics">{[['F1', metadata.test.f1], ['Precision', metadata.test.precision], ['Recall', metadata.test.recall], ['Average precision', metadata.test.average_precision]].map(([label, value]) => <article key={String(label)}><span>{String(label)}</span><strong>{pct(value as number)}</strong><small>held-out test</small></article>)}</section>
    <section className="model-grid"><article className="matrix-panel"><span className="kicker">Error profile</span><h2>Confusion matrix</h2><p>Counts from the {number(metadata.split.test_rows)} test rows.</p><div className="matrix"><span /><span>Predicted no</span><span>Predicted yes</span><span>Observed no</span><div className="matrix-good"><strong>{matrix.tn}</strong><small>True negatives</small></div><div className="matrix-warn"><strong>{matrix.fp}</strong><small>False positives</small></div><span>Observed yes</span><div className="matrix-warn"><strong>{matrix.fn}</strong><small>False negatives</small></div><div className="matrix-good"><strong>{matrix.tp}</strong><small>True positives</small></div></div></article>
      <article className="protocol-panel"><span className="kicker">Evaluation protocol</span><h2>Data split and threshold</h2><div className="protocol-flow"><div><Layers3 /><strong>{number(metadata.split.train_rows)}</strong><span>Train rows</span></div><i /><div><Target /><strong>{number(metadata.split.validation_rows)}</strong><span>Validation rows<br />threshold {metadata.winner.threshold.toFixed(3)}</span></div><i /><div><CheckCircle2 /><strong>{number(metadata.split.test_rows)}</strong><span>Test rows<br />final report</span></div></div><dl><div><dt>Candidate</dt><dd>{metadata.winner.spec.name}</dd></div><div><dt>Split seed</dt><dd>{metadata.split.seed}</dd></div><div><dt>Score type</dt><dd>Uncalibrated model score</dd></div><div><dt>Dataset fingerprint</dt><dd>{metadata.dataset.sha256.slice(0, 12)}…</dd></div></dl></article></section>
    <section className="evidence-section"><div><span className="kicker">Model comparison</span><h2>Top cross-validation results</h2><p>Candidates were evaluated with the same cross-validation folds.</p></div><div className="table-scroll"><table><caption>Top six candidate pipelines by cross-validation F1</caption><thead><tr><th>Candidate</th><th>CV F1</th><th>± SD</th><th>Precision</th><th>Recall</th><th>Avg. precision</th></tr></thead><tbody>{candidates.map((candidate) => <tr className={candidate.name === metadata.winner.spec.name ? 'selected-row' : ''} key={candidate.name}><th>{candidate.name}{candidate.name === metadata.winner.spec.name && <small>deployed</small>}</th><td>{pct(candidate.cv_f1_mean)}</td><td>{pct(candidate.cv_f1_std)}</td><td>{pct(candidate.cv_precision_mean)}</td><td>{pct(candidate.cv_recall_mean)}</td><td>{pct(candidate.cv_average_precision_mean)}</td></tr>)}</tbody></table></div></section>
    <section className="feature-policy"><div><span className="kicker">Input policy</span><h2>Model inputs</h2><p>The model uses 15 input fields. Age, marital status, and gender are excluded.</p></div><div className="feature-cloud">{publicFeatures.map((feature) => <span key={feature}>{pretty(feature)}</span>)}</div></section>
    <section className="limitations"><AlertTriangle /><div><h2>Limitations</h2><ul>{metadata.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
  </div>
}
